spin_version = "1"
authors = ["Phi Huynh <trumhemcut@hotmail.com>"]
description = ""
name = "spinwasi"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spinwasi"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
