apiVersion: apps/v1                                                  
kind: Deployment
metadata:
  name: bartholomew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bartholomew
  template:
    metadata:
      labels:
        app: bartholomew
    spec:
      runtimeClassName: wasmtime-spin
      containers:
      - name: bartholomew
        image: wasiacr.azurecr.io/bartholomew:latest
        command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: bartholomew
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: bartholomew