name = "bartholomew-template"
spin_version = "1"
version = "0.1.0"
description = "Your new Bartholomew website."
trigger = { type = "http", base = "/" }

[[component]]
source = "modules/bartholomew.wasm"
id = "bartholomew"
files = [ "content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]
[component.trigger]
route = "/..."
